FROM openjdk:12-jdk-alpine
ARG APP_GOOGLE_BOOKS_KEY
ARG APP_MOVIE_DATABASE_KEY
ARG SPRING_SENDGRID_API_KEY
ENV APP_GOOGLE_BOOKS_KEY $APP_GOOGLE_BOOKS_KEY
ENV APP_MOVIE_DATABASE_KEY $APP_MOVIE_DATABASE_KEY
ENV SPRING_SENDGRID_API_KEY $SPRING_SENDGRID_API_KEY
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*", "pl.fairit.somedayiwill.SomedayIWillApplication"]
