version: '3'

services:
  someday-mysql:
    restart: always
    container_name: someday-mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: someday-dev-db
      MYSQL_ROOT_PASSWORD: someday-db
      MYSQL_ROOT_HOST: '%'

    ports:
      - 6633:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=someday-db --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  someday-app:
    restart: on-failure
    build:
      dockerfile: Dockerfile-local
      context: .
      args:
        APP_GOOGLE_BOOKS_KEY:
        APP_MOVIE_DATABASE_KEY:
        SPRING_SENDGRID_API_KEY:
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: default
      WAIT_HOSTS: mysql:3306
    depends_on:
      - someday-mysql
